version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
shallow_clone: true
before_build:
  - nuget restore il2c.sln
build_script:
  - msbuild /t:Rebuild il2c.sln
  - cmd: pack.bat
artifacts:
  - path: artifacts
  - path: tests/IL2C.Core.Tests/bin/Debug/net462/translated
