version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
shallow_clone: true
before_build:
  - nuget restore il2c.sln
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"il2c" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=d160a9f1705a16193fb8b81164a3d6309ef4c841"
  - msbuild il2c.sln /t:Rebuild
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=d160a9f1705a16193fb8b81164a3d6309ef4c841"
  - cmd: pack.bat
artifacts:
  - path: artifacts
