version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: bash ./init-tools.sh
      - run: bash ./build-runtime.sh
      - run: bash ./pack.sh
    artifacts:
      - "artifacts"
