name: Windows
on:
  push:
    branches:
    - master
    - devel
    - feature/github-actions-2
  pull_request:
    branches:
    - master
    - devel
  workflow_dispatch:
    branches:
permissions:
  contents: read
jobs:
  build-windows:
    runs-on: [self-hosted, windows, x64]
    strategy:
      fail-fast: false
      matrix:
        buildConfiguration: [Debug, Release]
    env:
      buildConfiguration: ${{ matrix.buildConfiguration }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    # https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.*
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Initialize tools
      run: init-tools.bat
      shell: cmd
    - name: Install dependencies
      run: |
        msbuild -p:Configuration=${{env.buildConfiguration}} -t:restore il2c.sln
        msbuild -p:Configuration=${{env.buildConfiguration}} -t:restore samples\GettingStartedIL2C\GettingStartedIL2C.sln
        msbuild -p:Configuration=${{env.buildConfiguration}} -t:restore samples\Calculator\Calculator.sln
    #   dotnet restore il2c.sln
    #   dotnet restore samples\GettingStartedIL2C\GettingStartedIL2C.sln
    #   dotnet restore samples\Calculator\Calculator.sln
    - name: Build runtime library
      run: build-runtime.bat ${{env.buildConfiguration}}
      shell: cmd
    - name: Build il2c
      run: msbuild -p:Configuration=${{env.buildConfiguration}} -p:BuildIdentifier=$GITHUB_RUN_NUMBER -maxCpuCount il2c.sln
    - name: Build GettingStartedIL2C-x86
      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -p:Platform=x86 -maxCpuCount samples\GettingStartedIL2C\GettingStartedIL2C.sln
    - name: Build GettingStartedIL2C-x64
      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -p:Platform=x64 -maxCpuCount samples\GettingStartedIL2C\GettingStartedIL2C.sln
    - name: Build Calculator.Core
      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -maxCpuCount samples\Calculator\Calculator.Core\Calculator.Core.csproj
    - name: Build Calculator
      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -maxCpuCount samples\Calculator\Calculator\Calculator.csproj
#    - name: Build Calculator-x86
#      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -p:Platform=x86 -maxCpuCount samples\Calculator\Calculator.sln
#    - name: Build Calculator-x86
#      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -p:Platform=x86 -maxCpuCount samples\Calculator\Calculator.sln
#    - name: Build Calculator-x64
#      run: msbuild -p:Configuration=${{env.buildConfiguration}} -r:false -p:BuildIdentifier=$GITHUB_RUN_NUMBER -p:Platform=x64 -maxCpuCount samples\Calculator\Calculator.sln
#    - name: Build Calculator-CMake-mingw32
#      run: build.bat ${{env.buildConfiguration}}
#      shell: cmd
#      working-directory: samples\Calculator\Calculator.CMake
    - name: Test il2c
      run: dotnet test --no-build --verbosity normal --configuration ${{env.buildConfiguration}} tests\IL2C.Core.Test.Fixture\IL2C.Core.Test.Fixture.csproj -- BuildIdentifier=$GITHUB_RUN_NUMBER Platform=x64 CITest=True
      timeout-minutes: 20
