jobs:
  - job: Windows
    pool:
      vmImage: "windows-latest"
#   variables:
#     buildConfiguration: "Debug"
    steps:
      - script: |
          init-tools.bat
        displayName: "init-tools"
      - task: NuGetToolInstaller@0
        displayName: "Use nuget"
      - task: NuGetCommand@2
        displayName: "nuget restore il2c.sln"
        inputs:
          restoreSolution: "il2c.sln"
      - task: NuGetCommand@2
        displayName: "nuget restore GettingStartedIL2C.sln"
        inputs:
          restoreSolution: "samples/GettingStartedIL2C/GettingStartedIL2C.sln"
      - task: NuGetCommand@2
        displayName: "nuget restore Calculator.sln"
        inputs:
          restoreSolution: "samples/Calculator/Calculator.sln"
      - script: |
          build-runtime.bat $(buildConfiguration)
        displayName: "build-runtime"
      - task: MSBuild@1
        displayName: "build il2c"
        inputs:
          solution: "il2c.sln"
          configuration: "$(buildConfiguration)"
          platform: "Any Cpu"
          msbuildArguments: -p:BuildIdentifier="$(Build.BuildId)"
      - task: MSBuild@1
        displayName: "build GettingStartedIL2C-x86"
        inputs:
          solution: "samples/GettingStartedIL2C/GettingStartedIL2C.sln"
          configuration: "$(buildConfiguration)"
          platform: "x86"
          msbuildArguments: -p:BuildIdentifier="$(Build.BuildId)"
      - task: MSBuild@1
        displayName: "build GettingStartedIL2C-x64"
        inputs:
          solution: "samples/GettingStartedIL2C/GettingStartedIL2C.sln"
          configuration: "$(buildConfiguration)"
          platform: "x64"
          msbuildArguments: -p:BuildIdentifier="$(Build.BuildId)"
      - task: MSBuild@1
        displayName: "build Calculator-x86"
        inputs:
          solution: "samples/Calculator/Calculator.sln"
          configuration: "$(buildConfiguration)"
          platform: "x86"
          msbuildArguments: -p:BuildIdentifier="$(Build.BuildId)"
      - task: MSBuild@1
        displayName: "build Calculator-x64"
        inputs:
          solution: "samples/Calculator/Calculator.sln"
          configuration: "$(buildConfiguration)"
          platform: "x64"
          msbuildArguments: -p:BuildIdentifier="$(Build.BuildId)"
      - script: |
          build.bat $(buildConfiguration)
        displayName: "build Calculator-CMake-mingw32"
        workingDirectory: "samples/Calculator/Calculator.CMake"
      - task: VSTest@2
        displayName: "test il2c"
        inputs:
          testSelector: 'testAssemblies'
          vsTestVersion: '16.0'
          configuration: "$(buildConfiguration)"
          # http://hermit.no/how-to-resolve-cases-of-visual-studio-no-tests-appearing/
          platform: "x64"
          runInParallel: true
          testAssemblyVer2: "tests/IL2C.Core.Test.Fixture/bin/$(buildConfiguration)/**/IL2C.Core.Test.Fixture.dll"
