jobs:
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
#   variables:
#     buildConfiguration: "Release"
    steps:
      - script: |
          init-tools.bat
        displayName: "init-tools"
      - script: |
          pack.bat "$(Build.BuildId)"
        displayName: "pack"
#      - task: NuGetCommand@2
#        displayName: "nuget push"
#        inputs:
#          command: push
#          nuGetFeedType: external
#          publishFeedCredentials: $(NuGet.PushName)
