jobs:
  - job: Windows
    pool:
      vmImage: "windows-2019"
#   variables:
#     buildConfiguration: "Release"
    steps:
      - script: |
          init-tools.bat
        displayName: "init-tools"
      - task: DotNetCoreCLI@1
        displayName: "nuget restore il2c.sln"
        inputs:
          command: "restore"
          projects: "il2c.sln"
      - script: |
          build-runtime.bat Debug
        displayName: "build-runtime Debug"
      - script: |
          build-runtime.bat Release
        displayName: "build-runtime Release"
      - task: MSBuild@1
        displayName: "build il2c"
        inputs:
          solution: "il2c.sln"
          configuration: "Release"
          platform: "Any Cpu"
      - script: |
          ArtifactCollector\ArtifactCollector.exe . $(Build.ArtifactStagingDirectory) $(Build.BuildNumber) IL2C.Interop IL2C.Core IL2C.Tasks IL2C.Runtime
        displayName: "ArtifactCollector"
#      - task: NuGetCommand@2
#        displayName: "nuget push"
#        inputs:
#          command: push
#          nuGetFeedType: external
#          publishFeedCredentials: $(NuGet.PushName)
