jobs:
  - job: Windows
    condition: and(succeeded(), in(variables['Build.Reason'], 'BuildCompletion'))
    pool:
      vmImage: "windows-latest"
#   variables:
#     buildConfiguration: "Release"
    steps:
      - script: |
          init-tools.bat
        displayName: "init-tools"
      - script: |
          pack.bat "$(Build.BuildId)"
        displayName: "pack"
#      - task: NuGetCommand@2
#        displayName: "nuget push"
#        inputs:
#          command: push
#          nuGetFeedType: external
#          publishFeedCredentials: $(NuGet.PushName)
